version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: EventMarketplace.API/Dockerfile
    container_name: eventmarketplace-api
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: server=192.168.0.18;port=3306;user=root;password=Ok@n1984;database=EventMarketplaceDb;SslMode=none;
      Jwt__SecretKey: ${JWT_SECRET_KEY}
      Jwt__Issuer: EventMarketplace.Api
      Jwt__Audience: EventMarketplace.Client
      Jwt__AccessTokenExpirationMinutes: 60
      Jwt__RefreshTokenExpirationDays: 7
    ports:
      - "8080:8080"